#ifndef			TAS_APP_DSCADA_CTRL_ERROR_H
#define			TAS_APP_DSCADA_CTRL_ERROR_H

enum
{
	TAS_APP_DSCADA_CTRL_ERROR_CODE_BEGIN = 30001,

	TAS_APP_DSCADA_RECV_HEADER_DATA_FAILED,

	TAS_APP_DSCADA_INVALID_DATA_LEN,

	TAS_APP_DSCADA_RECV_DATA_FAILED,

	TAS_APP_DSCADA_WILL_LOST_CRITICAL_DATA,

	TAS_APP_DSCADA_START_FES_DATA_WORKER_FAILED,

	TAS_APP_DSCADA_CONN_FES_HANDSHAKE_STEP1_FAILED,

	TAS_APP_DSCADA_CONN_FES_HANDSHAKE_STEP2_FAILED,

	TAS_APP_DSCADA_CONN_FES_HANDSHAKE_FAILED,

	TAS_APP_DSCADA_START_PERSIST_SERVER_FAILED,

	TAS_APP_DSCADA_START_WARNING_WORKING_THREAD_FAILED,

	TAS_APP_DSCADA_CTRL_ERROR_CODE_END
};

typedef enum
{
	TAS_APP_DSCADA_FL_BEGIN = 31001,

	TAS_APP_DSCADA_LOAD_FAULT_LINK_TAB_FAILED,

	TAS_APP_DSCADA_LOAD_FAULT_NO_SEPC_NODE,

	TAS_APP_DSCADA_NOT_FOUND_NODE_IN_ACT_TREE,

	TAS_APP_DSCADA_FAULT_LOCATION_OVER,

	TAS_APP_DSCADA_FAULT_LOCATION_DEV_QUIT,

	TAS_APP_DSCADA_FAULT_LOCATION_NOT_FOUND_NODE_IN_LINKS_TABLE,

	TAS_APP_DSCADA_FL_END

}FAULT_LOCATION;


#endif